# This file was generated by GoReleaser. DO NOT EDIT.
cask "corral-sync" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "773ed984fdf16ee4445bf493ff2417888e75ed631e42c7c4141b0903d815abe6"
      url "https://github.com/sebastienrousseau/corral-sync/releases/download/v#{version}/corral-sync_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca8ccf162dc65f662234682a47f9afbe675cc5c0bd7af3aa7c972ee4c59bc226"
      url "https://github.com/sebastienrousseau/corral-sync/releases/download/v#{version}/corral-sync_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7f78f0016f816ef2f2e9e232745dc777816a5c403cd30e4754df2a570039e52"
      url "https://github.com/sebastienrousseau/corral-sync/releases/download/v#{version}/corral-sync_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b38bce51f0118fe4a2a0addf76494f5ee945b100dcff04cceb8e0ed240fdd53a"
      url "https://github.com/sebastienrousseau/corral-sync/releases/download/v#{version}/corral-sync_#{version}_linux_arm64.tar.gz"
    end
  end

  name "corral-sync"
  desc "Mirror a corral tree to GitLab and Gitea"
  homepage "https://github.com/sebastienrousseau/corral-sync"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corral-sync"

  # No zap stanza required

end
