# This file was generated by GoReleaser. DO NOT EDIT.
cask "corralctl" do
  version "0.0.25"

  on_macos do
    on_arm do
      sha256 "2493d48071077056884ba67b6774157b1a5fb41590b5429e4262b404cec8badd"
      url "https://github.com/sebastienrousseau/corral/releases/download/v#{version}/corralctl_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "668c4420d8830f124033521620bc412ab4a9ca098552e89fec9c626f15781646"
      url "https://github.com/sebastienrousseau/corral/releases/download/v#{version}/corralctl_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0b9fc3ed8c3d93449789f9ea7b2a4a42cb68ed2c697c50cc806c8e8a3868b97a"
      url "https://github.com/sebastienrousseau/corral/releases/download/v#{version}/corralctl_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1be3b9c904a2b2b843d0b08757ee91180b49dd5d66015ddd5b2e2518d5ad0d5"
      url "https://github.com/sebastienrousseau/corral/releases/download/v#{version}/corralctl_Linux_x86_64.tar.gz"
    end
  end

  name "corralctl"
  desc "Automatically clone and organise GitHub repositories by visibility and language"
  homepage "https://github.com/sebastienrousseau/corral"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corralctl"

  # No zap stanza required
end
