# This file was generated by GoReleaser. DO NOT EDIT.
cask "corralctl" do
  version "0.0.42"

  on_macos do
    on_arm do
      sha256 "cb007e1866bc3c5042c0ea651137cb8048cea00ff1e2201c769532e075622644"
      url "https://github.com/sebastienrousseau/corralctl/releases/download/v#{version}/corralctl_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5aff307ba2a891dd7cd87d93ae3456d13ba30dbfc246875ed1b33339d208beba"
      url "https://github.com/sebastienrousseau/corralctl/releases/download/v#{version}/corralctl_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "58db01944ffcc8dd1eb6d49d4c0b3fd02cc459ecf8eb3657f4ad2f41dae37e8a"
      url "https://github.com/sebastienrousseau/corralctl/releases/download/v#{version}/corralctl_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc264c797163d3ca414334421b54e5ef699fb3b71251cedd37555c0bdaef8241"
      url "https://github.com/sebastienrousseau/corralctl/releases/download/v#{version}/corralctl_Linux_x86_64.tar.gz"
    end
  end

  name "corralctl"
  desc "Clone and organise repositories from GitHub, GitLab, Gitea, Forgejo, Codeberg and Bitbucket by visibility and language, then let your AI coding agent search across all of them at once, straight from disk."
  homepage "https://github.com/sebastienrousseau/corralctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corralctl"

  # No zap stanza required
end
