# This file was generated by GoReleaser. DO NOT EDIT.
cask "corralctl" do
  version "0.0.22"

  on_macos do
    on_intel do
      sha256 "55af7c99c7dfd3ec4fb0ce99180a3dcc503e29f29a4454cddc628826cd92f232"
      url "https://github.com/sebastienrousseau/corral/releases/download/v#{version}/corralctl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2a02ee392c10f41d62ea64042afbc15d58705ad79d97afd0c9bf9953752f8648"
      url "https://github.com/sebastienrousseau/corral/releases/download/v#{version}/corralctl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57eb0a9dcfa4d50860e64fb8c8b06961279799ba077a7a9cacbf8b7e2993bfca"
      url "https://github.com/sebastienrousseau/corral/releases/download/v#{version}/corralctl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c3c8a95d0e58130879a32c6c5d8684b7ed24f381365d9b447628cb6a737af97e"
      url "https://github.com/sebastienrousseau/corral/releases/download/v#{version}/corralctl_Linux_arm64.tar.gz"
    end
  end

  name "corralctl"
  desc "Automatically clone and organise GitHub repositories by visibility and language."
  homepage "https://github.com/sebastienrousseau/corral"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "corralctl"

  # No zap stanza required

end
