# This file was generated by GoReleaser. DO NOT EDIT.
cask "passmcp" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "passmcp"], chdir: "."
  end

  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "ea317aad0e2ed27f580332e6209e80cfde66da6476eb7cd8ba9b974df799df40"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "42dd2729c5fd42f9fb0c3a88c4f4a6ed279bf37b3b3093049c71a7cac39b0cf2"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "71ae581ebc02252c3d8df1e7b2f458ac78069c7ac5ae237014f3c880c7a4945a"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "95a2b27aba6ead514ebf0a35a334451b8808cac0faa9791225e6ec0fd2ef2568"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Linux_x86_64.tar.gz"
    end
  end

  name "passmcp"
  desc "Onboard, test and diagnose remote MCP servers end to end"
  homepage "https://github.com/sebastienrousseau/passmcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passmcp"
  manpage "man/passmcp.1"
  bash_completion "completions/passmcp.bash"
  fish_completion "completions/passmcp.fish"
  zsh_completion "completions/passmcp.zsh"

  # No zap stanza required
end
