# This file was generated by GoReleaser. DO NOT EDIT.
cask "passmcp" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "passmcp"], chdir: "."
  end

  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "b6eac8521d89d6ea3b015be3848f5cbe672ac8fffbbc275eb5a289c54a333415"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a9a5f04c4c773272caabba9e0e413474892c14c54efa4f52c425aedae40e888"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "42979f263c0eb976299e09d459742c3efe3b5e3bda24fcc54b118e62795efe8b"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2384fec12887e9ed29417c9c84c02eee67feea0974307d4919dd1e766a6b2608"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Linux_x86_64.tar.gz"
    end
  end

  name "passmcp"
  desc "Onboard, test and diagnose remote MCP servers end to end"
  homepage "https://github.com/sebastienrousseau/passmcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passmcp"
  manpage "man/passmcp.1"
  bash_completion "completions/passmcp.bash"
  fish_completion "completions/passmcp.fish"
  zsh_completion "completions/passmcp.zsh"

  # No zap stanza required
end
