# This file was generated by GoReleaser. DO NOT EDIT.
cask "passmcp" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "passmcp"], chdir: "."
  end

  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "f2bebd53b546bf53114a71338ca95eae92616169a43cc6a11bf8624a4a188bd4"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "416c8b1926f4fa718b62b96314483cbd6eba5d5cd7a0fca1247d755e23c17342"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "900345540f7d44c2733505684102c9e626fc523030a6dfdb17bcc33caa26ad2d"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0de90ca35c23ae1fb9252852baf3d962b1c716bcaf8715f5fb5ac30222221bde"
      url "https://github.com/sebastienrousseau/passmcp/releases/download/v#{version}/passmcp_Linux_x86_64.tar.gz"
    end
  end

  name "passmcp"
  desc "Onboard, test and diagnose remote MCP servers end to end"
  homepage "https://github.com/sebastienrousseau/passmcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "passmcp"
  manpage "man/passmcp.1"
  bash_completion "completions/passmcp.bash"
  fish_completion "completions/passmcp.fish"
  zsh_completion "completions/passmcp.zsh"

  # No zap stanza required
end
