# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "scout"], chdir: "."
  end

  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "984e410cc177dc12109bb8bc3092ba2ee8922e71f4a2c4ad20ac462a3d7cd823"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b1d75a2bcf663c67da6c822ef2444a96cad8a7951ed52b3c62a8f30f27457295"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8061cf4a24656bf755d428f499bd71ba2c6efd0cf1bf7f4dbd8a0e0999626231"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9602a05394c7a0f725abaa101ff7170be7aedb642139cdd66f1f09feaba166f2"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Linux_x86_64.tar.gz"
    end
  end

  name "scout"
  desc "Onboard, test and diagnose remote MCP servers end to end"
  homepage "https://github.com/sebastienrousseau/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"
  manpage "man/scout.1"
  bash_completion "completions/scout.bash"
  fish_completion "completions/scout.fish"
  zsh_completion "completions/scout.zsh"

  # No zap stanza required
end
