# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "scout"], chdir: "."
  end

  version "0.0.5"

  on_macos do
    on_arm do
      sha256 "de9ffafe24f39209c9abce746d36aeacd9c0f409fcfc6453c44d4a9eb7c28fcf"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d0dc427a9223502c9abafdac43b10a6ca55fe0cb98319f41328f77db14d59fd6"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "790b685d7ac75cb0fb95f65aac832405ee1a6b161c57462da675a20c4603c263"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5eb83087669ac6412c65198932a14b3ee001275ed4003c3cdf4d10761d1ad32a"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Linux_x86_64.tar.gz"
    end
  end

  name "scout"
  desc "Onboard, test and diagnose remote MCP servers end to end"
  homepage "https://github.com/sebastienrousseau/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"
  manpage "man/scout.1"
  bash_completion "completions/scout.bash"
  fish_completion "completions/scout.fish"
  zsh_completion "completions/scout.zsh"

  # No zap stanza required
end
