# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "scout"], chdir: "."
  end

  version "0.0.6"

  on_macos do
    on_arm do
      sha256 "3a6eba51dedf0daed2268818ed1f7153064db88f17590d159d59e79445fcc84d"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1896710a2a88d9f9704dd5e06badae720ff51cd55b2e004b682cb25c1427708"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ca13ab85fa9142941ab0fc6c2c58813ce794d1878ce7b28295871c8bff5035dd"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ecacf475b56227169c17e5e8e2fbfeed15eb3a3e1ba58a974f12579fb3695b62"
      url "https://github.com/sebastienrousseau/scout/releases/download/v#{version}/scout_Linux_x86_64.tar.gz"
    end
  end

  name "scout"
  desc "Onboard, test and diagnose remote MCP servers end to end"
  homepage "https://github.com/sebastienrousseau/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"
  manpage "man/scout.1"
  bash_completion "completions/scout.bash"
  fish_completion "completions/scout.fish"
  zsh_completion "completions/scout.zsh"

  # No zap stanza required
end
