# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corralctl < Formula
  desc "Automatically clone and organise GitHub repositories by visibility and language."
  homepage "https://github.com/sebastienrousseau/corral"
  version "0.0.11"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.11/corralctl_Darwin_x86_64.tar.gz"
      sha256 "9f0980c8fde1fd7e63ece9727a02e34a719678deb59f2263d915d81dec90a1b9"

      define_method(:install) do
        bin.install "corralctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.11/corralctl_Darwin_arm64.tar.gz"
      sha256 "a7ecd93eec9f90243b59dee39e8ac1a638976bcf00179fb51fe1df965538a9b2"

      define_method(:install) do
        bin.install "corralctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.11/corralctl_Linux_x86_64.tar.gz"
      sha256 "99f711d99027952a40451b3cdd168349e8ff6f2717cc5e942bd554f04646d85d"
      define_method(:install) do
        bin.install "corralctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.11/corralctl_Linux_arm64.tar.gz"
      sha256 "75e12d9bf2215ebf19f44a5cee37555c00c051e9be2cc8b25bc48baa6e993c9e"
      define_method(:install) do
        bin.install "corralctl"
      end
    end
  end

  test do
    system "#{bin}/corralctl --help"
  end
end
