# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corral < Formula
  desc "Automatically clone and organise GitHub repositories by visibility and language."
  homepage "https://github.com/sebastienrousseau/corral"
  version "0.0.4"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.4/corral_Darwin_x86_64.tar.gz"
      sha256 "dedcc07e84c813561918142bdc8e1d0807f0cba60fd1eb4c905d91f74da21d89"

      define_method(:install) do
        bin.install "corral"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.4/corral_Darwin_arm64.tar.gz"
      sha256 "98bc11ae5c5c0504f306029109a97bbf62aa693cc121a4f6ee1c0f51d23bdb20"

      define_method(:install) do
        bin.install "corral"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.4/corral_Linux_x86_64.tar.gz"
      sha256 "e48a1c88759229ed754323000fd42c25329d56b9840c5f9b20f6bd69e6f223d5"
      define_method(:install) do
        bin.install "corral"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.4/corral_Linux_arm64.tar.gz"
      sha256 "ce2705575e3380239f586575ad505c82562a2965736878a9f0cfad93bb118d14"
      define_method(:install) do
        bin.install "corral"
      end
    end
  end

  test do
    system "#{bin}/corral --help"
  end
end
