# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corral < Formula
  desc "Automatically clone and organise GitHub repositories by visibility and language."
  homepage "https://github.com/sebastienrousseau/corral"
  version "0.0.2"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.2/corral_Darwin_x86_64.tar.gz"
      sha256 "c83390bc8f49b39b81eed2ea1d0af686804b78867ff0e64139eadfc35b760e06"

      define_method(:install) do
        bin.install "corral"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.2/corral_Darwin_arm64.tar.gz"
      sha256 "4d9bf7afe40305d66ed243586f610a96537d301e8c734e87a987f495c4e3efd4"

      define_method(:install) do
        bin.install "corral"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.2/corral_Linux_x86_64.tar.gz"
      sha256 "a4d1d6d76c502ebed31ca53bdb2ca1bef2f918df896ea2fee7ae41c1bf81e1ff"
      define_method(:install) do
        bin.install "corral"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebastienrousseau/corral/releases/download/v0.0.2/corral_Linux_arm64.tar.gz"
      sha256 "31ef09839778d6c97c7c789052ac4ef579269732935998610f657da48f4f7c33"
      define_method(:install) do
        bin.install "corral"
      end
    end
  end

  test do
    system "#{bin}/corral --help"
  end
end
