# typed: false
# frozen_string_literal: true

# SPDX-License-Identifier: MIT
#
# Stratos — official command-line client for CloudCDN.
#
# Generated by stratos itself at release time. The homebrew-tap repo
# auto-syncs this file from the GitHub release.
#
# Project home: https://github.com/sebastienrousseau/stratos

class Stratos < Formula
  desc "Official command-line client for CloudCDN"
  homepage "https://github.com/sebastienrousseau/stratos"
  version "0.0.14"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.14/stratos-darwin-arm64"
      sha256 "656398a8804465ead5554b796e9aa09d66a98d92865344097d8f443abfce8f66"
    end
    on_intel do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.14/stratos-darwin-x64"
      sha256 "3db0597753d6a12c5a57850018fda22e2d1332f159769e63b24da7bf8212361b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.14/stratos-linux-arm64"
      sha256 "97e1a5a76c6ae35161cf8a6afa19391c777fd02eaf0059575d3feaa123d78605"
    end
    on_intel do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.14/stratos-linux-x64"
      sha256 "92a971f05d1deeed0b0811fc3a681e1cdf1ef5d37a746a352645a74f6132d73d"
    end
  end

  def install
    binary_name = case [OS.kernel_name, Hardware::CPU.arch].join("-")
                  when "Darwin-arm64" then "stratos-darwin-arm64"
                  when "Darwin-x86_64" then "stratos-darwin-x64"
                  when "Linux-arm64" then "stratos-linux-arm64"
                  when "Linux-x86_64" then "stratos-linux-x64"
                  end
    bin.install binary_name => "stratos"
  end

  test do
    assert_match "stratos v0.0.14", shell_output("#{bin}/stratos version")
  end
end
