# typed: false
# frozen_string_literal: true

# SPDX-License-Identifier: MIT
#
# Stratos — official command-line client for CloudCDN.
#
# Generated by stratos itself at release time. The homebrew-tap repo
# auto-syncs this file from the GitHub release.
#
# Project home: https://github.com/sebastienrousseau/stratos

class Stratos < Formula
  desc "Official command-line client for CloudCDN"
  homepage "https://github.com/sebastienrousseau/stratos"
  version "0.0.17"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.17/stratos-darwin-arm64"
      sha256 "5bd480342591234999bce961a453d2b64d8c1e292e3e8296a2f31cbd4421fe62"
    end
    on_intel do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.17/stratos-darwin-x64"
      sha256 "7ed9aadc2bfa4d762586c65fb7d3bb93290a85a80141b92a461bf39fcb88117c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.17/stratos-linux-arm64"
      sha256 "61f9957ddd4c6f12653bb072fa0fcfc36f6a37bb36e8a125799173bd4dd7c022"
    end
    on_intel do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.17/stratos-linux-x64"
      sha256 "f35aa0c01de7a60ddea28fd5b6c102a2dedda6d09184bd60b7fe6c8ee90a7e4c"
    end
  end

  def install
    binary_name = case [OS.kernel_name, Hardware::CPU.arch].join("-")
                  when "Darwin-arm64" then "stratos-darwin-arm64"
                  when "Darwin-x86_64" then "stratos-darwin-x64"
                  when "Linux-arm64" then "stratos-linux-arm64"
                  when "Linux-x86_64" then "stratos-linux-x64"
                  end
    bin.install binary_name => "stratos"
  end

  test do
    assert_match "stratos v0.0.17", shell_output("#{bin}/stratos version")
  end
end
