# typed: false
# frozen_string_literal: true

# SPDX-License-Identifier: MIT
#
# Stratos — official command-line client for CloudCDN.
#
# Generated by stratos itself at release time. The homebrew-tap repo
# auto-syncs this file from the GitHub release.
#
# Project home: https://github.com/sebastienrousseau/stratos

class Stratos < Formula
  desc "Official command-line client for CloudCDN"
  homepage "https://github.com/sebastienrousseau/stratos"
  version "0.0.21"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.21/stratos-darwin-arm64"
      sha256 "b29ff783d5602df1c868709a9909e0c5ad5dd6680497af48a5ba8da47d3ca636"
    end
    on_intel do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.21/stratos-darwin-x64"
      sha256 "1a9e55763331d357a15e33febeccf93af4ee2b6b495a2439830f46ace3fae806"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.21/stratos-linux-arm64"
      sha256 "0578a2230e643de880d1c5d9535bc5f0c2c00307d5c4daa90d990eece5a06e54"
    end
    on_intel do
      url "https://github.com/sebastienrousseau/stratos/releases/download/v0.0.21/stratos-linux-x64"
      sha256 "0028d7fa3507ca8cdc6d607ebe99c75ac8b9036a02f05ac55eb41ba575edfe6c"
    end
  end

  def install
    binary_name = case [OS.kernel_name, Hardware::CPU.arch].join("-")
                  when "Darwin-arm64" then "stratos-darwin-arm64"
                  when "Darwin-x86_64" then "stratos-darwin-x64"
                  when "Linux-arm64" then "stratos-linux-arm64"
                  when "Linux-x86_64" then "stratos-linux-x64"
                  end
    bin.install binary_name => "stratos"
  end

  test do
    assert_match "stratos v0.0.21", shell_output("#{bin}/stratos version")
  end
end
